/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospital.emergency.ui;

import hospital.emergency.EmergencyRoom.EmergencyRoom;

/**
 *
 * @author amir
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    final EmergencyRoom room;
    public MainFrame(EmergencyRoom room) {
        initComponents();
        this.room = room;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_register_patient = new javax.swing.JButton();
        btn_managment = new javax.swing.JButton();
        btMRecord = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnRegisterStaff = new javax.swing.JButton();
        btBedAdd = new javax.swing.JButton();
        btnRealesePatient = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("مدیریت اورژانس");
        setSize(new java.awt.Dimension(500, 500));

        btn_register_patient.setText("ثبت بیمار جدید");
        btn_register_patient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_register_patientMouseClicked(evt);
            }
        });

        btn_managment.setText("مدیریت");
        btn_managment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_managmentActionPerformed(evt);
            }
        });

        btMRecord.setText("ثبت یا ویرایش پرونده پزشکی");
        btMRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMRecordActionPerformed(evt);
            }
        });

        jLabel1.setText("بخش اورژانس");

        btnRegisterStaff.setText("ثبت کارمند");
        btnRegisterStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterStaffActionPerformed(evt);
            }
        });

        btBedAdd.setText("افزایش تخت");
        btBedAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBedAddActionPerformed(evt);
            }
        });

        btnRealesePatient.setText("ترخیص بیمار");
        btnRealesePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealesePatientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btMRecord)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRegisterStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnRealesePatient, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btBedAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btn_register_patient, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_managment, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel1)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_managment)
                    .addComponent(btn_register_patient))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRealesePatient)
                    .addComponent(btBedAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btMRecord)
                    .addComponent(btnRegisterStaff))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_register_patientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_register_patientMouseClicked
        // TODO add your handling code here:
        RegisterPatientFrame frame = new RegisterPatientFrame(this.room);
        frame.setVisible(true);
    }//GEN-LAST:event_btn_register_patientMouseClicked

    private void btn_managmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_managmentActionPerformed
        // TODO add your handling code here:
        ManagmentFrame frame = new ManagmentFrame(room);
        frame.setVisible(true);
    }//GEN-LAST:event_btn_managmentActionPerformed

    private void btnRegisterStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterStaffActionPerformed
        // TODO add your handling code here:
        RegisterStaffFrame frame = new RegisterStaffFrame(room);
        frame.setVisible(true);
    }//GEN-LAST:event_btnRegisterStaffActionPerformed

    private void btBedAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBedAddActionPerformed
        // TODO add your handling code here:
        AddBedFrame frame = new AddBedFrame(room);
        frame.setVisible(true);
    }//GEN-LAST:event_btBedAddActionPerformed

    private void btnRealesePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealesePatientActionPerformed
        // TODO add your handling code here:
        releasePatientFrame frame = new releasePatientFrame(room);
        frame.setVisible(true);
    }//GEN-LAST:event_btnRealesePatientActionPerformed

    private void btMRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMRecordActionPerformed
        MedicalRecordFrame frame = new MedicalRecordFrame(room);
        frame.setVisible(true);
    }//GEN-LAST:event_btMRecordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBedAdd;
    private javax.swing.JButton btMRecord;
    private javax.swing.JButton btnRealesePatient;
    private javax.swing.JButton btnRegisterStaff;
    private javax.swing.JButton btn_managment;
    private javax.swing.JButton btn_register_patient;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
