/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospital.emergency.ui;

import hospital.emergency.EmergencyRoom.Bed;
import hospital.emergency.EmergencyRoom.EmergencyRoom;
import hospital.emergency.patient.Patient;
import hospital.emergency.staff.Staff;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author amir
 */
public class ManagmentFrame extends javax.swing.JFrame {

    /**
     * Creates new form ManagmentFrame
     */
    final EmergencyRoom room;
    public ManagmentFrame(EmergencyRoom room) {
        initComponents();
        this.room= room;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_patient = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePatients = new javax.swing.JTable();
        lbl_beds = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_beds = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableQueu = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableStaffs = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("مدیرت اوژانس");

        lbl_patient.setText("لیست بیماران");

        jTablePatients.setModel(updateTablePatient());
        jScrollPane1.setViewportView(jTablePatients);

        lbl_beds.setText("لیست تخت ها");

        jTable_beds.setModel(updateTableBeds());
        jScrollPane2.setViewportView(jTable_beds);

        jLabel1.setText("لیست انتظار");

        jTableQueu.setModel(updateTableQueueً());
        jScrollPane3.setViewportView(jTableQueu);

        jLabel2.setText("لیست کارمندان");

        jTableStaffs.setModel(updateTableStaff());
        jScrollPane4.setViewportView(jTableStaffs);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbl_patient)
                                .addGap(14, 14, 14))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_beds, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lbl_patient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_beds)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public DefaultTableModel updateTablePatient() {
    String[] columns = {"ID","نام","جنست","سن","شدت"};
    DefaultTableModel newModel = new DefaultTableModel(columns, 0);

    // فقط نگاه می‌کنیم بدون حذف بیماران از صف
    for (Patient p : room.patients) {
        newModel.addRow(new Object[]{
            p.getId(),
            p.getName(),
            p.getGen(),
            p.getAge(),
            p.getSeverityLevel().name()
        });
    }

    return (newModel);
    }
    
    
    public DefaultTableModel updateTableBeds() {
    String[] columns = {"ID","تخصیص داده"};
    DefaultTableModel newModel = new DefaultTableModel(columns, 0);

    // فقط نگاه می‌کنیم بدون حذف بیماران از صف
    String x = "";
    for (Bed b : room.bedsMg.beds) {
        if(b.getAssignedPatient() == null)
            x = "خیر";
        else {x = String.valueOf(b.assignedPatient.getId());}
        newModel.addRow(new Object[]{
            b.getId(),
            x
        });
    }

    return (newModel);
    }

    
    public DefaultTableModel updateTableQueueً() {
    String[] columns = {"ID","نام","جنست","سن","شدت"};
    DefaultTableModel newModel = new DefaultTableModel(columns, 0);

    // فقط نگاه می‌کنیم بدون حذف بیماران از صف
    for (Patient p : room.queue.getall()) {
        newModel.addRow(new Object[]{
            p.getId(),
            p.getName(),
            p.getGen(),
            p.getAge(),
            p.getSeverityLevel().name()
        });
    }

    return (newModel);
    }
    
    public DefaultTableModel updateTableStaff() {
    String[] columns = {"ID","نام","شیفت","نقش",};
    DefaultTableModel newModel = new DefaultTableModel(columns, 0);

    // فقط نگاه می‌کنیم بدون حذف بیماران از صف
    for (Staff s: room.staffs ){
        newModel.addRow(new Object[]{
            s.getId(),
            s.getName(),
            s.getShift(),
            s.getRole()
        });
    }

    return (newModel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTablePatients;
    private javax.swing.JTable jTableQueu;
    private javax.swing.JTable jTableStaffs;
    private javax.swing.JTable jTable_beds;
    private javax.swing.JLabel lbl_beds;
    private javax.swing.JLabel lbl_patient;
    // End of variables declaration//GEN-END:variables
}
