/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospital.emergency.ui;

import hospital.emergency.EmergencyRoom.EmergencyRoom;
import hospital.emergency.patient.Patient;
import hospital.emergency.patient.SeverityLevel;
import javax.swing.JOptionPane;

/**
 *
 * @author amir
 */
public class RegisterPatientFrame extends javax.swing.JFrame {

    /**
     * Creates new form RegisterPatientFrame
     */
    final EmergencyRoom room;
    public RegisterPatientFrame(EmergencyRoom roomٍ) {
        initComponents();
        this.room = roomٍ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_register = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        tf_name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cb_gen = new javax.swing.JComboBox<>();
        tf_age = new javax.swing.JTextField();
        ckb_needbed = new javax.swing.JCheckBox();
        tf_Family = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rbSeverityL = new javax.swing.JRadioButton();
        rbServrityM = new javax.swing.JRadioButton();
        rbSeverityH = new javax.swing.JRadioButton();
        rbSeverityC = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ثبت بیمار جدید");
        setSize(new java.awt.Dimension(480, 350));

        jLabel1.setText("مشخصات بیمار");

        jLabel2.setText("نام :");

        btn_register.setText("ثبت");
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });

        jButton2.setText("خروج");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("جنسیت:");

        jLabel5.setText("سن:");

        cb_gen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "آقا", "خانم" }));

        ckb_needbed.setText("نیاز به تخت؟");

        jLabel6.setText("نام خانوادگی");

        jLabel3.setText("شدت وضعیت:");

        rbSeverityL.setText("کم");
        rbSeverityL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSeverityLActionPerformed(evt);
            }
        });

        rbServrityM.setText("متوسط");
        rbServrityM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbServrityMActionPerformed(evt);
            }
        });

        rbSeverityH.setText("زیاد");
        rbSeverityH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSeverityHActionPerformed(evt);
            }
        });

        rbSeverityC.setText("حاد");
        rbSeverityC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSeverityCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ckb_needbed)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_register)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_name)
                            .addComponent(tf_Family)
                            .addComponent(cb_gen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf_age)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(100, Short.MAX_VALUE)
                        .addComponent(rbSeverityC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbSeverityH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbServrityM)
                        .addGap(12, 12, 12)
                        .addComponent(rbSeverityL)
                        .addGap(34, 34, 34)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_Family, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_gen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rbSeverityL)
                    .addComponent(rbServrityM)
                    .addComponent(rbSeverityH)
                    .addComponent(rbSeverityC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ckb_needbed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_register)
                    .addComponent(jButton2))
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    SeverityLevel severityLevel ;
    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
        // TODO add your handling code here:
            if(tf_age.getText().isEmpty() || tf_Family.getText().isEmpty() || tf_name.getText().isEmpty() || severityLevel == null) {
        JOptionPane.showMessageDialog(
            this,
            "همه موارد را کامل کنید.",
            "خطا",
            JOptionPane.ERROR_MESSAGE
        );
    } else {
        try {
            String name = tf_name.getText();
            String family = tf_Family.getText();
            int age = Integer.parseInt(tf_age.getText().trim());
            String gender = cb_gen.getSelectedItem().toString();
            boolean needBed = ckb_needbed.isSelected();

            Patient patient = new Patient(name, family, age, gender,severityLevel, needBed);
            room.registerPatient(patient);

            JOptionPane.showMessageDialog(
                this,
                "بیمار با موفقیت ثبت شد.",
                "موفقیت",
                JOptionPane.INFORMATION_MESSAGE
            );

            // اگر میخوای فرم رو بعد ثبت پاک کنی:
            tf_name.setText("");
            tf_Family.setText("");
            tf_age.setText("");
            ckb_needbed.setSelected(false);
            cb_gen.setSelectedIndex(0);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                this,
                "لطفا شناسه و سن را به صورت عددی وارد کنید.",
                "خطا",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }
    }//GEN-LAST:event_btn_registerActionPerformed

    private void rbSeverityLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSeverityLActionPerformed
        // TODO add your handling code here:
        rbServrityM.setSelected(false);
        rbSeverityH.setSelected(false);
        rbSeverityC.setSelected(false);
        severityLevel =  SeverityLevel.LOW;

    }//GEN-LAST:event_rbSeverityLActionPerformed

    private void rbServrityMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbServrityMActionPerformed
        // TODO add your handling code here:
        rbSeverityL.setSelected(false);
        rbSeverityH.setSelected(false);
        rbSeverityC.setSelected(false);
        severityLevel =  SeverityLevel.MEDIUM;
    }//GEN-LAST:event_rbServrityMActionPerformed

    private void rbSeverityHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSeverityHActionPerformed
        // TODO add your handling code here:
        rbServrityM.setSelected(false);
        rbSeverityL.setSelected(false);
        rbSeverityC.setSelected(false);
        severityLevel =  SeverityLevel.HIGH;
    }//GEN-LAST:event_rbSeverityHActionPerformed

    private void rbSeverityCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSeverityCActionPerformed
        // TODO add your handling code here:
        rbSeverityL.setSelected(false);
        rbSeverityH.setSelected(false);
        rbServrityM.setSelected(false);
        severityLevel =  SeverityLevel.CRITICAL;
    }//GEN-LAST:event_rbSeverityCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterPatientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterPatientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterPatientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterPatientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_register;
    private javax.swing.JComboBox<String> cb_gen;
    private javax.swing.JCheckBox ckb_needbed;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton rbServrityM;
    private javax.swing.JRadioButton rbSeverityC;
    private javax.swing.JRadioButton rbSeverityH;
    private javax.swing.JRadioButton rbSeverityL;
    private javax.swing.JTextField tf_Family;
    private javax.swing.JTextField tf_age;
    private javax.swing.JTextField tf_name;
    // End of variables declaration//GEN-END:variables
}
